blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('',views.bloghome, name='bloghome'),
    path('<str:cmd>/<int:fa>/<int:la>/',views.bloghome, name='bloghome'), #fa ->first article of page, la->last article
    path('article/',views.article, name='article'),
    path('article/<int:pk>/',views.article, name='article'),
    path('postLike/',views.postLike,name='postLike'), #aid->article id
    path('getLikeCount/',views.getLikeCount,name='getLikeCount'),
    path('postComment/',views.postComment,name='postComment'),
    path('getComments/',views.getComments,name='getComments'),
    path('getAccountStats/',views.getAccountStats,name='getAccountStats')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('MayaChatbot/',include('MayaChatbot.urls')),
]

blog/models.py
from django.db import models
# from accounts.models import RegisterUser
from django.conf import settings
from datetime import datetime

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    tags = models.CharField(max_length=100,null=True)
    author = models.CharField(max_length=50)
    pub_date = models.DateField(auto_now_add=True)
    # likes = models.IntegerField(default=0)
    
    def short_desc(self):
        return self.description[:200]+'....'
    
    def __str__(self):
        return self.title

# model to store article likes
class ArticleLikes(models.Model):
    article_id = models.ForeignKey(Article,on_delete=models.CASCADE )
    liked_by_username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

# model to store article comments
class ArticleComment(models.Model):
    article_id = models.ForeignKey(Article,on_delete=models.CASCADE )
    commented_by_username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment_description = models.TextField(max_length=300)

    def __str__(self):
        return  "Article:->"+str(self.article_id.title) + " ||  Comment:->  "+self.comment_description

blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import ArticleComment

class CommentForm(ModelForm):
    class Meta:
        model = ArticleComment
        fields = ['comment_description']
        widgets = {
            'comment_description':forms.Textarea(
                attrs={
                    'class':'form-control',
                    'placeholder':'Leave a comment'
                }
            )
        }

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.core import serializers
from .models import Article, ArticleLikes,ArticleComment
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import CommentForm

import json
from django.core.serializers.json import DjangoJSONEncoder
# Create your views here.

def bloghome(request,cmd=None,fa=None,la=None):
    articles = Article.objects.all()
    articles = sorted(articles,key = lambda x:x.pub_date,reverse=True)
    if request.method=='POST':
        searchkey = request.POST.get('searchblog').lower()
        searchedArtl = []
        ct = 0

        for artl in articles:
            if searchkey in artl.title.lower() or searchkey in artl.tags.lower():
                searchedArtl.append(artl)
                ct+=1
            if ct>50:
                break

        context = {
            'articles':searchedArtl,
            'btn_display':False,
        }
        return render(request,'blog/index.html',context)
    else:   
       
        if cmd=='prev':
            if fa <= 0 or fa-5 <=0:
                fa=0
                la=4
            elif fa-5>=0:
                fa = fa -5
                la = la -5
        elif cmd == 'next':
            if (la >= len(articles)-1) or (la + 5 > len(articles)):
                fa = len(articles)-5
                la = len(articles)-1
            else:
                fa = la+1
                la = la+5
        else:
            fa = 0
            la = 4
        
        articles = articles[fa:la+1]

        context = {
            'articles':articles,
            'first_article': articles[0].id-1,
            'last_article': articles[len(articles)-1].id-1,
            'btn_display':True,
        }

    return render(request,'blog/index.html',context)



def article(request,pk=None):
    if pk == None:
        return bloghome(request)

    article = Article.objects.get(id=pk)

    context= {
        'article':article,
        'comment_form': CommentForm()
    }
    return render(request,'blog/display_single_article.html',context)


@login_required(login_url='/accounts/loginForm')
def postLike(request):
    if request.method == 'POST':
        if request.is_ajax():
            username = request.POST['username']
            userObj = User.objects.get(username=username)

            aid = int(request.POST['aid'])
            aIdObj = Article.objects.get(id=aid)

            if len(ArticleLikes.objects.filter(article_id=aIdObj, liked_by_username=userObj)) < 1:
                obj = ArticleLikes(article_id=aIdObj,liked_by_username=userObj)
                obj.save()                   
            total_likes = len(ArticleLikes.objects.filter(article_id=aIdObj))
            return HttpResponse(total_likes)


@login_required(login_url='/accounts/loginForm')
def getLikeCount(request):
    if request.method == 'POST':
        if request.is_ajax():
            aid = int(request.POST['aid'])
            aIdObj = Article.objects.get(id=aid)
            total_likes = len(ArticleLikes.objects.filter(article_id=aIdObj))

            return HttpResponse(total_likes)   


@login_required(login_url='/accounts/loginForm')
def postComment(request):
    if request.method == 'POST':     
        if request.is_ajax():
            cmnt_desc = request.POST['cmnt_desc']
            artl = int(request.POST['artl_id'])
            username = request.POST['username']
            
            artl_obj = Article.objects.get(id=artl)
            user_obj = User.objects.get(username=username)

            frm = ArticleComment(article_id = artl_obj, commented_by_username=user_obj, comment_description=cmnt_desc)
            frm.save()
            
    return HttpResponse('success')


@login_required(login_url='/accounts/loginForm')
def getComments(request):
    if request.method == 'POST':
        if request.is_ajax():
            artl = int(request.POST['artl_id'])
            artl_obj = Article.objects.get(id=artl)

            data = ArticleComment.objects.filter(article_id=artl_obj).values('article_id__id','commented_by_username__username','comment_description')
            # print(data)
            data = json.dumps(list(reversed(data)), cls=DjangoJSONEncoder)

    return JsonResponse({'all_artl_comments':data})


@login_required(login_url='/accounts/loginForm')
def getAccountStats(request):
    if request.method == 'POST':
        total_article_count = len(Article.objects.all())
        total_comment_count = len(ArticleComment.objects.filter(commented_by_username__username=request.user.username))
        total_like_count = len( ArticleLikes.objects.filter(liked_by_username__username= request.user.username) )

        context = {
            'total_article_count':total_article_count,
            'total_comment_count':total_comment_count,
            'total_like_count':total_like_count,
        }

        return JsonResponse(context)
    return render(request,'accounts/loginForm.html')

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %} {% endblock%}  </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- <link rel="" > -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel='stylesheet' href="{% static 'css/nav_style.css' %}">
        <link rel='stylesheet' href="{% static 'css/index_style.css' %}">
    </head>

    <body>
        {% include 'blog/nav.html' %}

        {% block content %}        {% endblock%}

        {% include 'core/footer.html' %}
        
        <!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="{% static 'js/fixedNav.js' %}"></script>
        <script async src="https://static.addtoany.com/menu/page.js"></script>
        <!-- <script src="{% static 'js/postlike.js' %}"></script> -->
        <script>

            // post request to save a users like
          $("#like-btn").click(function(){
                $.post(
                    'http://127.0.0.1:8000/blog/postLike/',
                    {
                        username: '{{request.user.username}}',
                        aid: {{article.id}},
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    function(data){
                        $('#like-count').html(data);
                    });
            });


        // post request to get counting of likes on article

        $(document).ready(function(){
                $.post(
                    'http://127.0.0.1:8000/blog/getLikeCount/',
                    {
                        aid:{{article.id}},
                        'csrfmiddlewaretoken':'{{ csrf_token }}',
                    },
                    function(data){
                            $('#like-count').html(data);
                });
            });

        // hide comment box on initial load

        $(document).ready(function(){
            $('#comment-form').hide();
            $('#all-comment').hide();
            getcomments();
        });

        // open comment box when clicked on comment button

        $(document).ready(function(){
            $('#comment-btn').click(function(){
                $('#comment-form').toggle();
                $('#all-comment').toggle();
                
            });
        });

        // function to get comments
        function getcomments(){
            $.post(
                    'http://127.0.0.1:8000/blog/getComments/',
                    {
                        'artl_id':{{article.id}},
                        'csrfmiddlewaretoken':'{{ csrf_token }}'
                    },
                    function(data){              
                        var instance = JSON.parse(data['all_artl_comments']);                        
                        // console.log(instance);
                        html_data = `<p><b>Comments : </b></p>`;
                        instance.forEach(element => {

                            html_data += `<div id='single-comment' class='bg-light mt-2 p-2'>
                                <small><b><i class='fa fa-user-circle'></i> ${element['commented_by_username__username']}</b></small><br>
                                <i><span class='fa fa-comment'></span> ${element['comment_description']}</i>
                            </div> `;
                        });
                        $('#all-comment').html( html_data);
                });
        }

        // submit/post comment when clicked om post button

        $(document).ready(function(){
            $('#submit-comment').click(function(){
                $.post(
                    'http://127.0.0.1:8000/blog/postComment/',
                    {
                        'cmnt_desc':$('#id_comment_description').val(),
                        'artl_id':{{article.id}},
                        'username': '{{request.user.username}}',
                        'csrfmiddlewaretoken':'{{ csrf_token }}'
                    },
                    function(data){
                        $('#id_comment_description').val("");
                        getcomments();

                });
            });
        });
        </script>
        <script>
            $("#move-to-top").click(function() {
              $("html, body").animate({ scrollTop: 0 }, "slow");
                return false;
            });
        </script>
    </body>

</html>

templates/blog/display_single_article.html
{% extends 'blog/base.html' %} {% block title %} {{article.title}} {% endblock %} {% block content %}
<div id='main' style="width: 80%; margin:auto;">
    <div class="container">
        <h1 class='fadein mb-5 mt-5 text-center' id='art_title'> {{article.title}} </h1>
        <p><i>Published : {{article.pub_date}}</i></p>
        <p><small>Tags: {{article.tags}}</small></p>
        <p class="text-justify">{{article.description|safe}}</p>
        <p>Thanks,</p>
        <h5>{{article.author}}</h5>
    </div>

    <div class="container row mt-5 text-center">
        {% if request.user.is_authenticated %}
        <div class="col col-lg-3 col-md-6 col-sm-6 mt-2">
            <button class="btn btn-danger" id='like-btn'><i class="fa fa-heart" ></i> <span id='like-count'></span></button>
        </div>

        <div class="col col-lg-3 col-md-6 col-sm-6 mt-2">
            <button class="btn btn-info" id='comment-btn'><i class="fa fa-comment"></i> Comment</button>
        </div>
        {% endif %}

        <div class="col col-lg-6 col-md-12 col-sm-12 mt-2 ">
            <span><b>Share:</b></span>
            <div class="a2a_kit a2a_kit_size_32 a2a_default_style float-right">
                <!-- <a class="a2a_dd" href="https://www.addtoany.com/share"></a> -->
                <a class="a2a_button_facebook"></a>
                <a class="a2a_button_twitter"></a>
                <a class="a2a_button_linkedin"></a>
                <a class="a2a_button_whatsapp"></a>
                <a class="a2a_button_telegram"></a>
                <!-- <a class="a2a_button_buffer"></a> -->
                <a class="a2a_button_facebook_messenger"></a>
                <a class="a2a_button_pinterest"></a>
                <a class="a2a_button_email"></a>
            </div>

            <!-- AddToAny END -->
        </div>
    </div>
    {% if request.user.is_authenticated %}
    <div id="comment-form" class="container w-75 m-auto">
        {{comment_form.as_p}}
        <button class="btn btn-primary" id='submit-comment'>Post</button>
    </div>
    <!-- div to show all comment -->
    <div id='all-comment' class="container w-75 m-auto mt-5">

    </div>
    {% endif %} {% if request.user.is_authenticated == False %}
    <p><b><i class='text-danger'>Please Login to Like and Comment </i></b></p>
    {% endif %}
</div>


{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %} Blog {% endblock %}
{% block content %}
<div id='main' style="width: 80%; margin:auto;">
    <h1 class='fadein mb-5 mt-5'>My Blog/Articles</h1>
    
    {% if btn_display %}
    <div class="row">
        <div class="col col-lg-3 col-md-4 col-sm-3">
        <a href="{% url 'bloghome' cmd='prev' fa=first_article la=last_article %}" class="btn btn-outline-secondary" >&larr; Prev</a>
        </div>
        <!-- search form -->
        <div class="col col-lg-6 col-md-4 col-sm-6">
        <form class="form-inline w-50 m-auto" method="POST" action="{%url 'bloghome' %}">
            {% csrf_token %}
            <input class="form-control border-0" type="text" name="searchblog" placeholder="Search Blog"/>
            <button class="form-control border-0 ml-1" type='submit' value="Search" ><i class="fa fa-search"></i></button>
        </form>
        </div>

        <div class="col col-lg-3 col-md-4 col-sm-3">
        <a href="{% url 'bloghome' cmd='next' fa=first_article la=last_article %}" class="btn btn-outline-secondary float-right">Next &rarr;</a>
        </div>

    </div>
    <hr>
    {% endif%}


    {% for article in articles %}
    <div class="container mt-5 shadow-sm p-3 mb-5 bg-white rounded">
        <h2><a href="{% url 'article' pk=article.id %}" id='art_title'>{{article.title}}</a></h2>
        <p><i>{{article.pub_date}}</i></p>
        <p>{{article.short_desc}}<a href="{% url 'article' pk=article.id %}">Read Full Article</a></p>
        <p>Tags: <i>{{article.tags}}</i></p>
    </div>
    <!-- <hr> -->
    {% endfor %}
    {% if btn_display %}
    <div>
        <a href="{% url 'bloghome' cmd='prev' fa=first_article la=last_article %}" class="btn btn-outline-secondary" >&larr; Prev</a>
        <a href="{% url 'bloghome' cmd='next' fa=first_article la=last_article %}" class="btn btn-outline-secondary float-right">Next &rarr;</a>

    </div>
    <hr>
    {% endif %}

</div>
{% endblock %}

templates/blog/nav.html
<div id='navbar_top' class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <h1 class="navbar-brand">
        <i class="fa fa-star"></i> Welcome {{request.user.username}} <i class="fa fa-star"></i>
    </h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        
        <li class="nav-item">
            <a class="nav-link " href="{% url 'home' %}"><b>Home</b></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'contact'%}"><b>Contact</b></a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" href="{% url 'education'%}"><b>Education</b></a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" href="{% url 'experience'%}"><b>Experience</b></a>
        </li>    
        <li class="nav-item"> 
            <a  class="nav-link" href="{% url 'skills'%}"><b>Skills</b></a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" href="{% url 'workdone'%}"><b>My Work</b></a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" href="{% url 'bloghome'%}"><b>Blog</b></a>
        </li>  
        {% if request.user.is_authenticated == True %}
            <!-- <li class="nav-item tel-no btn btn-outline-danger" id='login-btn'>
                <a class="nav-link " href="{% url 'logoutUser' %}"> <span></span> <b>Logout</b></a>
            </li> -->
            <li class="nav-item dropdown dropleft">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <b>Account</b>
                </a>
                <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'profile' username=request.user.username %}"><i class="fa fa-user-circle"></i> Profile</a>
                  <a class="dropdown-item" href="{% url 'logoutUser' %}"><i class="fa fa-sign-out"></i> Logout</a>                  
                </div>
              </li>


        {% else %}
            <li class="nav-item tel-no btn btn-outline-info" id='login-btn'>
                <a class="nav-link " href="{% url 'loginForm' %}"> <span class="fa fa-sign-in"></span> <b>Login</b></a>
            </li>
            <li class="nav-item tel-no btn btn-outline-success" id='reg-btn'>
                <a class="nav-link " href="{% url 'registerForm' %}"> <span class="fa fa-user-plus"></span> <b>Register</b></a>
            </li>
        {% endif %}
    </ul>
    </div>

</div>